apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-02-22T10:50:03Z"
  generation: 48
  name: pacman
  namespace: argocd
  resourceVersion: "34202"
  uid: 2540abdc-89c8-45ce-aa4a-2387619b6b0c
spec:
  destination:
    namespace: pacman-argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: pacman-app/
    repoURL: https://github.com/arblCTW/pacman-app-argocd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2024-02-22T10:53:15Z"
    deployedAt: "2024-02-22T10:53:15Z"
    id: 0
    revision: 047b1b4006e32e95cfe843dcb993b18197a5b135
    source:
      path: pacman-app/
      repoURL: https://github.com/arblCTW/pacman-app-argocd
      targetRevision: HEAD
  - deployStartedAt: "2024-02-22T10:56:43Z"
    deployedAt: "2024-02-22T10:56:45Z"
    id: 1
    revision: 9d74414e1e72fdbc64bcb599a4f32990b019f8b6
    source:
      path: pacman-app/
      repoURL: https://github.com/arblCTW/pacman-app-argocd
      targetRevision: HEAD
  operationState:
    finishedAt: "2024-02-22T10:56:45Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        prune: true
        revision: 9d74414e1e72fdbc64bcb599a4f32990b019f8b6
        syncOptions:
        - CreateNamespace=true
        - Replace=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2024-02-22T10:56:43Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/pacmanservice replaced
        name: pacmanservice
        namespace: pacman-argo
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/pacman replaced
        name: pacman
        namespace: pacman-argo
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/hello replaced
        name: hello
        namespace: default
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/pacman replaced
        name: pacman
        namespace: pacman-argo
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 9d74414e1e72fdbc64bcb599a4f32990b019f8b6
      source:
        path: pacman-app/
        repoURL: https://github.com/arblCTW/pacman-app-argocd
        targetRevision: HEAD
  reconciledAt: "2024-02-22T11:03:11Z"
  resources:
  - health:
      status: Healthy
    kind: Service
    name: pacmanservice
    namespace: pacman-argo
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: hello
    namespace: default
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: pacman
    namespace: pacman-argo
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: pacman
    namespace: pacman-argo
    status: Synced
    version: v1
  sourceType: Directory
  summary:
    externalURLs:
    - http://pacman.local/pacman-path
    images:
    - ghcr.io/arblctw/pacman:2.0
    - hashicorp/http-echo
  sync:
    comparedTo:
      destination:
        namespace: pacman-argo
        server: https://kubernetes.default.svc
      source:
        path: pacman-app/
        repoURL: https://github.com/arblCTW/pacman-app-argocd
        targetRevision: HEAD
    revision: 9d74414e1e72fdbc64bcb599a4f32990b019f8b6
    status: Synced
